name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['debug', 'release']
        compiler: ['gcc', 'clang']
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: build
      run: 
        CC=${{matrix.compiler}}
        CONFIGURATION=${{matrix.configuration}}
        source ./github_build.sh
    - name: test
      run: 
        CONFIGURATION=${{matrix.configuration}}
        if [ ${{matrix.compiler}} == 'gcc' ] && [ ${{matrix.configuration} == 'release' ]; then
          SLANG_TEST_CATEGORY=full
          SLANG_DEPLOY=true
        else
          SLANG_TEST_CATEGORY=smoke
          SLANG_DEPLOY=false
        fi
        source ./github_test.sh